# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

variables:
  IMAGE_NAME: "unyleyaregistry.azurecr.io/azure-vote"
  TAG: '$(Build.BuildId)'
  FULL_IMAGE_NAME: '$(IMAGE_NAME):$(TAG)'

stages:
- stage: BuildAndPush
  displayName: "Build and Push Docker Image"
  jobs:
  - job: Build
    displayName: "Build and Push Docker Image"
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: "UnyleyaAzureContainerRegistry"
        scriptType: "bash"
        scriptLocation: "inlineScript"
        inlineScript: |
          echo "Logging into Azure Container Registry"
          az acr login --name unyleyaregistry

          echo "Building the Docker image"
          docker build -f '$(Build.SourcesDirectory)/azure-vote/Dockerfile' -t $FULL_IMAGE_NAME .

          echo "Pushing the Docker image $FULL_IMAGE_NAME"
          docker push $FULL_IMAGE_NAME

          echo "Docker image pushed: $FULL_IMAGE_NAME"

          docker images

    # Instalar o Helm
    - task: HelmInstaller@1
      displayName: 'Install Helm'
      inputs:
        version: '3.x'  # Especifica a versão do Helm a ser instalada

    # Adicionar o repositório Helm e instalar o chart (caso necessário)
    - script: |
        echo "Adding Helm chart repository..."
        helm repo add stable https://charts.helm.sh/stable
        helm repo update

      displayName: "Install Helm Chart"

    - script: echo "Pipeline Build and Push completed successfully!"
      displayName: "Completion Message"
